export const skillIcons = [
  {
    src: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original-wordmark.svg',
    alt: 'react-icon',
    name: 'React.js',
    className: 'pointer-events-none',
  },
  {
    src: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg',
    alt: 'js-icon',
    name: 'JavaScript',
    className: 'pointer-events-none',
  },
  {
    src: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/typescript/typescript-original.svg',
    alt: 'ts-icon',
    name: 'TypeScript',
    className: 'pointer-events-none',
  },
  {
    src: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/php/php-original.svg',
    alt: 'php-icon',
    name: 'PHP',
    className: 'pointer-events-none',
  },
  {
    src: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/java/java-original.svg',
    alt: 'java-icon',
    name: 'Java',
    className: 'pointer-events-none',
  },
  {
    src: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg',
    alt: 'css-icon',
    name: 'CSS',
    className: 'pointer-events-none',
  },
  {
    src: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg',
    alt: 'html-icon',
    name: 'HTML',
    className: 'pointer-events-none',
  },
  {
    src: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/sass/sass-original.svg',
    alt: 'sass-icon',
    name: 'SASS',
    className: 'pointer-events-none',
  },
  {
    src: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/redux/redux-original.svg',
    alt: 'redux-icon',
    name: 'Redux',
    className: 'pointer-events-none',
  },
  {
    src: 'https://www.vectorlogo.zone/logos/tailwindcss/tailwindcss-icon.svg',
    alt: 'twind-icon',
    name: 'Tailwind',
    className: 'pointer-events-none',
  },
  {
    src: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original-wordmark.svg',
    alt: 'node-icon',
    name: 'Node.js',
    className: 'pointer-events-none',
  },
  {
    src: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/express/express-original-wordmark.svg',
    alt: 'xpress-icon',
    name: 'Express',
    className: 'pointer-events-none dark:invert',
  },
  {
    src: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/mongodb/mongodb-original-wordmark.svg',
    alt: 'mongo-db',
    name: 'mongoDB',
  },
  {
    src: 'https://www.vectorlogo.zone/logos/jestjsio/jestjsio-icon.svg',
    alt: 'jest-icon',
    name: 'Jest',
  },
  {
    src: 'https://cdn.worldvectorlogo.com/logos/nextjs-2.svg',
    alt: 'next-icon',
    name: 'Next.js',
    className: 'pointer-events-none dark:invert',
  },
];
